### ISSUE TITLE
TypeError: Cannot set property 'subscribeLinearPrivate' of null

### ISSUE THREAD

**Issue by emorling** [tiagosiebler/bybit-api#244]
This seems to be happening every now and then when the web socket reconnects. Any idea what the issue may be?

`

2023-03-26 04:30:32 8e57ae09c3e5 [
2023-03-26 04:30:32 8e57ae09c3e5   'Websocket connection closed',
2023-03-26 04:30:32 8e57ae09c3e5   { category: 'bybit-ws', wsKey: 'linearPrivate' }
2023-03-26 04:30:32 8e57ae09c3e5 ]
2023-03-26 04:30:33 8e57ae09c3e5 [
2023-03-26 04:30:33 8e57ae09c3e5   'Reconnecting to websocket',
2023-03-26 04:30:33 8e57ae09c3e5   { category: 'bybit-ws', wsKey: 'linearPrivate' }
2023-03-26 04:30:33 8e57ae09c3e5 ]
2023-03-26 04:30:33 8e57ae09c3e5 [
2023-03-26 04:30:33 8e57ae09c3e5   "Getting auth'd request params",
2023-03-26 04:30:33 8e57ae09c3e5   { category: 'bybit-ws', wsKey: 'linearPrivate' }
2023-03-26 04:30:33 8e57ae09c3e5 ]
2023-03-26 04:30:33 8e57ae09c3e5 [
2023-03-26 04:30:33 8e57ae09c3e5   'Websocket reconnected',
2023-03-26 04:30:33 8e57ae09c3e5   { category: 'bybit-ws', wsKey: 'linearPrivate' }
2023-03-26 04:30:33 8e57ae09c3e5 ]
2023-03-26 04:30:34 8e57ae09c3e5 response {
2023-03-26 04:30:34 8e57ae09c3e5   success: true,
2023-03-26 04:30:34 8e57ae09c3e5   ret_msg: '',
2023-03-26 04:30:34 8e57ae09c3e5   conn_id: '99aed0e5-0e13-47b8-b6cc-e51b5baeac1f',
2023-03-26 04:30:34 8e57ae09c3e5   request: { op: 'subscribe', args: [ 'position', 'order' ] },
2023-03-26 04:30:34 8e57ae09c3e5   wsKey: 'linearPrivate'
2023-03-26 04:30:34 8e57ae09c3e5 }
2023-03-26 04:30:34 8e57ae09c3e5 [
2023-03-26 04:30:34 8e57ae09c3e5   'Failed to parse ws event message',
2023-03-26 04:30:34 8e57ae09c3e5   {
2023-03-26 04:30:34 8e57ae09c3e5     category: 'bybit-ws',
2023-03-26 04:30:34 8e57ae09c3e5     error: TypeError: Cannot set property 'subscribeLinearPrivate' of null
2023-03-26 04:30:34 8e57ae09c3e5         at WebsocketClient.<anonymous> (/data/app/dist/ws/bybit-socket.js:227:137)
2023-03-26 04:30:34 8e57ae09c3e5         at WebsocketClient.emit (events.js:315:20)
2023-03-26 04:30:34 8e57ae09c3e5         at WebsocketClient.onWsMessage (/data/app/node_modules/bybit-api/lib/websocket-client.js:496:26)
2023-03-26 04:30:34 8e57ae09c3e5         at WebSocket.ws.onmessage (/data/app/node_modules/bybit-api/lib/websocket-client.js:452:40)
2023-03-26 04:30:34 8e57ae09c3e5         at WebSocket.onMessage (/data/app/node_modules/ws/lib/event-target.js:132:16)
2023-03-26 04:30:34 8e57ae09c3e5         at WebSocket.emit (events.js:315:20)
2023-03-26 04:30:34 8e57ae09c3e5         at Receiver.receiverOnMessage (/data/app/node_modules/ws/lib/websocket.js:1068:20)
2023-03-26 04:30:34 8e57ae09c3e5         at Receiver.emit (events.js:315:20)
2023-03-26 04:30:34 8e57ae09c3e5         at Receiver.dataMessage (/data/app/node_modules/ws/lib/receiver.js:517:14)
2023-03-26 04:30:34 8e57ae09c3e5         at /data/app/node_modules/ws/lib/receiver.js:468:23,
2023-03-26 04:30:34 8e57ae09c3e5     event: MessageEvent {
2023-03-26 04:30:34 8e57ae09c3e5       target: [WebSocket],
2023-03-26 04:30:34 8e57ae09c3e5       type: 'message',
2023-03-26 04:30:34 8e57ae09c3e5       data: '{"success":true,"ret_msg":"","conn_id":"99aed0e5-0e13-47b8-b6cc-e51b5baeac1f","request":{"op":"subscribe","args":["position","order"]}}'
2023-03-26 04:30:34 8e57ae09c3e5     },
2023-03-26 04:30:34 8e57ae09c3e5     wsKey: 'linearPrivate'
2023-03-26 04:30:34 8e57ae09c3e5   }
2023-03-26 04:30:34 8e57ae09c3e5 ]

`

**Comment by tiagosiebler** [comment]
Hey @emorling - the stack trace suggests a possible direction to investigate from:
```
error: TypeError: Cannot set property 'subscribeLinearPrivate' of null
at WebsocketClient. (/data/app/dist/ws/bybit-socket.js:227:137)
at WebsocketClient.emit (events.js:315:20)
at WebsocketClient.onWsMessage (/data/app/node_modules/bybit-api/lib/websocket-client.js:496:26)
```

- Ws client saw and emitted a message
- Your event consumer seems to be in your `ws/bybit-socket` file.
- Do you have a call there to `subscribeLinearPrivate`? 

It might be a scope issue, if you show a bit of code around line 227 in that file, I can take a look?

The "Failed to parse ws event message" error is a bit misleading here, since in this case it just means when the ws client called the emit function on the event emitter, the consumer threw an unhandled exception and the only place that caught it was the ws client.

**Comment by emorling** [comment]
Thanks, you were right. This was an error in my script using the lib. I solved it thanks to your comments!
