### ISSUE TITLE
Error connecting from an Google Compute Engine instance to Bybit

### ISSUE THREAD

**Issue by ralvs** [tiagosiebler/bybit-api#268]
Hello guys.

I'm testing a script with using WebsocketClient to listen to new orders of my account.
Running it on my machine is fine.
But trying to run in a Compute Engine instance, it can't connect.

Any idea why?

Compute Engine is configured with fixed ip address. 
And I don't think it is a firewall problem because the connection is originating from the instance so the firewall usually doesn't block the response.

```
[
  "Getting auth'd request params",
  { category: 'bybit-ws', wsKey: 'v5Private' }
]
[
  'Websocket onWsError due to unexpected response error: "Unexpected server response: 403"',
  {
    category: 'bybit-ws',
    wsKey: 'v5Private',
    error: ErrorEvent {
      target: [WebSocket],
      type: 'error',
      message: 'Unexpected server response: 403',
      error: Error: Unexpected server response: 403
          at ClientRequest.<anonymous> (/home/renanmalves/octopusTrader/node_modules/ws/lib/websocket.js:783:7)
          at ClientRequest.emit (node:events:513:28)
          at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
          at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
          at TLSSocket.socketOnData (node:_http_client:542:22)
          at TLSSocket.emit (node:events:513:28)
          at addChunk (node:internal/streams/readable:324:12)
          at readableAddChunk (node:internal/streams/readable:297:9)
          at Readable.push (node:internal/streams/readable:234:10)
          at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
    }
  }
]
[
  'unhandled onWsError - closing socket to reconnect',
  {
    category: 'bybit-ws',
    wsKey: 'v5Private',
    reason: 'unhandled onWsError'
  }
]
[
  'unhandled onWsError - socket already closed - trigger immediate reconnect',
  {
    category: 'bybit-ws',
    wsKey: 'v5Private',
    reason: 'unhandled onWsError'
  }
]
error ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      message: [Function],
      error: [Function],
      close: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://stream-testnet.bybit.com/v5/private?api_key=cNAjbL9beI3tFOVr8O&expires=1686855658411&signature=816bb2b63177c92c9cedda3748526045660cdceb53e9bdf47d3c39742ea3f7e4',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /v5/private?api_key=cNAjbL9beI3tFOVr8O&expires=1686855658411&signature=816bb2b63177c92c9cedda3748526045660cdceb53e9bdf47d3c39742ea3f7e4 HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: jHzvaE1feKYvqtTRm5kbqw==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Host: stream-testnet.bybit.com\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v5/private?api_key=cNAjbL9beI3tFOVr8O&expires=1686855658411&signature=816bb2b63177c92c9cedda3748526045660cdceb53e9bdf47d3c39742ea3f7e4',
      _ended: false,
      res: [IncomingMessage],
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'stream-testnet.bybit.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kError)]: undefined
    },
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'Unexpected server response: 403',
  error: Error: Unexpected server response: 403
      at ClientRequest.<anonymous> (/home/renanmalves/octopusTrader/node_modules/ws/lib/websocket.js:783:7)
      at ClientRequest.emit (node:events:513:28)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at TLSSocket.socketOnData (node:_http_client:542:22)
      at TLSSocket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
}
[
  'Websocket connection closed',
  { category: 'bybit-ws', wsKey: 'v5Private' }
]
[
  'Reconnecting to websocket',
  { category: 'bybit-ws', wsKey: 'v5Private' }
]
[
  'Refused to connect to ws, connection attempt already active',
  { category: 'bybit-ws', wsKey: 'v5Private' }
]

```

**Comment by ralvs** [comment]
Read that could be something related to params `origin` or `check_origin`
But I don't know where or how to specify them

**Comment by tiagosiebler** [comment]
Is your instance using a US IP? API calls from US IPs are blocked on most exchanges, sadly.

**Comment by ralvs** [comment]
Oh Gosh, it works !!! 
Can't believe I have spent 2 days fighting with this error 😅
Thank you so much!

**Comment by tiagosiebler** [comment]
> Oh Gosh, it works !!! Can't believe I have spent 2 days fighting with this error 😅 Thank you so much!

Wasn't immediately obvious though the 403 error code suggested it was something auth/permission related! Glad that helped!
